const DEVELOPMENT_DOMAIN = ``;
const DOMAIN = process.env.GATSBY_URL_BASE || DEVELOPMENT_DOMAIN;
const PUBLIC_DOMAIN = process.env.GATSBY_PUBLIC_DOMAIN || null;
const BOOLEAN_ECNRYPTION = process.env.GATSBY_ENCRYPTION_API === "false";
const ENABLE_ENCRYPTION = BOOLEAN_ECNRYPTION;

const BASE_URL = DOMAIN;

export default { ENABLE_ENCRYPTION, PUBLIC_DOMAIN, DOMAIN, BASE_URL };
