import { lightGray, whiteText, black, primary } from "@constants/colors";

const BREAKPOINTS = [320, 640, 980, 1280, 1540];
const BREAKPOINTS_PREFIX = ["xs", "sm", "md", "lg", "xl"];

const alias = {
	maxw: "max-width",
	minw: "min-width",
	maxh: "max-height",
	minh: "min-height",
	size: "font-size",
	order: "order",
	weight: "font-weight",
	family: "font-family",
	decoration: "text-decoration",
	spacing: "letter-spacing",
	justify: "justify-content",
	items: "align-items",
	content: "align-content",
	direction: "flex-direction",
	align: "text-align",
	flexalign: ["align-items", "align-content", "justify-content"],
	pv: ["padding-top", "padding-bottom"],
	ph: ["padding-left", "padding-right"],
	mv: ["margin-top", "margin-bottom"],
	mh: ["margin-left", "margin-right"],
	wsvg: ["width", "height", "min-width", "min-height"],
	dimentions: ["width", "height", "min-width", "min-height"],
	$height: ["height", "max-height"],
	spacing: "letter-spacing",
	pl: "padding-left",
	pr: "padding-right",
	ml: "margin-left",
	mr: "margin-right",
	pt: "padding-top",
	pb: "padding-bottom",
	mt: "margin-top",
	mb: "margin-bottom",
	ttrans: "text-transform",
	cols: "grid-template-columns",
	acols: "grid-auto-columns",
	rows: "grid-template-row",
	arows: "grid-auto-rows",
	colstart: "grid-column-start",
	colend: "grid-column-end",
	rowstart: "grid-row-start",
	rowend: "grid-row-end",
	col: "grid-column",
	row: "grid-row",
	radius: "border-radius",
	filter: "backdrop-filter",
	decorator: "text-decoration"
};

const values = {
	around: "space-around",
	between: "space-between",
	start: "flex-start",
	startSnap: "start",
	end: "flex-end",
	primary: primary,
	secondary: black,
	white: whiteText,
	black: black,
	light: lightGray,
	blue: "rgb(50, 100, 255)",
	upper: "uppercase",
	lower: "lowercase",
	black_20: "rgb(from black r g b / 20%)",
	black_40: "rgb(from black r g b / 40%)",
	black_60: "rgb(from black r g b / 60%)",
	black_80: "rgb(from black r g b / 80%)",
	white_20: "rgb(from white r g b / 20%)",
	white_40: "rgb(from white r g b / 40%)",
	white_60: "rgb(from white r g b / 60%)",
	white_80: "rgb(from white r g b / 80%)",
	primary_20: `rgb(from ${primary} r g b / 20%)`,
	primary_40: `rgb(from ${primary} r g b / 40%)`,
	primary_60: `rgb(from ${primary} r g b / 60%)`,
	primary_80: `rgb(from ${primary} r g b / 80%)`,
	scrollStart: 'start',
	scrollEnd: 'end',
	scrollCenter: 'center'
};

export default {
	alias,
	values,
	BREAKPOINTS,
	BREAKPOINTS_PREFIX,
};
